import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { Content } from "~/components/Content";
import Header from "~/components/Header";

export default function Home() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Notetaker T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {sessionData?.user ? (
          <Content />
        ) : (
          <div className="flex h-screen flex-col items-center justify-center">
            <p className="mb-10 text-2xl">Sign in to view your notes</p>
            <button className="btn btn-primary" onClick={() => void signIn()}>
              Sign in
            </button>
          </div>
        )}
      </main>
    </>
  );
}
