import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import Header from "~/components/Header";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Notetaker T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
}

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: topics, refresh: refreshTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
    },
  );

  return <div>{JSON.stringify(topics)}</div>;
};
